version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GIN_MODE=release
    id: "anipm"
    binary: anipm
    main: ./main.go
    flags:
      - -trimpath
    ldflags:
      - -s -w
    targets:
      - windows_amd64
      - linux_amd64
      - darwin_arm64
upx:
  - enabled: true
    goos: [windows, linux]
    compress: best
    lzma: true
archives:
  - files:
      - LICENSE
      - README.md
      - templates/*
      - VERSION
    format: tar.gz
    name_template: |
      {{- if .IsSnapshot -}}
        {{ .Binary }}_snapshot_{{ .Os }}_{{ .Arch }}_{{ .ShortCommit }}
      {{- else -}}
        {{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
      {{- end -}}
release:
  replace_existing_artifacts: true
  prerelease: auto
  mode: replace
checksum:
  split: true
