name: snapshot

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  publish:
    concurrency:
      group: snapshot
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make upx
          VERSION="$(<VERSION)"
          git tag -d "$VERSION" | true
          git tag "$VERSION" | true
          git push origin "$VERSION" --force | true

      - name: Build Client
        run: |
          npm install -g pnpm
          pnpm -C ./anipm-client i
          pnpm -C ./anipm-client run build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
